name: pubspec # Le nom de votre projet.

description: Gestion pubspec # Une courte description de votre projet.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# La ligne ci-dessus indique où vous souhaitez publier votre package.
# Dans ce cas, la valeur est "none", ce qui signifie que vous ne voulez pas publier votre package sur pub.dev.

version: 1.0.0+1 # La version actuelle de votre package.
# Dans ce cas, la version est 1.0.0+1. Le +1 indique qu'il s'agit de la première version de votre package.

environment:
  sdk: '>=2.18.5 <3.0.0' # La version minimale de l'`SDK` (`Software Development Kit`) nécessaire pour exécuter votre package.
  # Dans ce cas, la version minimale est 2.18.5 et la version maximale est 3.0.0.

dependencies:
  flutter:
    sdk: flutter # Les dépendances sont les packages externes nécessaires à l'exécution de votre projet.
    # Dans ce cas, la dépendance est flutter.

  cupertino_icons: ^1.0.2 # La dépendance pour l'utilisation des icônes Cupertino.

dev_dependencies:
  flutter_test:
    sdk: flutter # Les dépendances de développement sont des packages externes nécessaires uniquement pour le développement de votre projet.
    # Dans ce cas, la dépendance de développement est flutter_test.

  flutter_lints: ^2.0.0 # La dépendance de développement pour l'utilisation de linter.

flutter:
  uses-material-design: true # Paramètres pour la configuration de votre application Flutter.
  # Dans ce cas, il utilise le design Material.
